version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: sev_helper_db
    environment:
      POSTGRES_DB: sev_helper
      POSTGRES_USER: sev_user
      POSTGRES_PASSWORD: sev_pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
